#!/usr/bin/env python3
"""
Index builder — generates topic `_index.md` files and cross-topic indexes
from article YAML frontmatter (see .kb/index-formats.md).

Generated files carry the marker "<!-- generated by index_builder.py -->".
Files without the marker (hand-curated, e.g. techniques) are NEVER overwritten
unless --force is given. Run after every compile/write (graph_generator runs too).

Usage:
    python index_builder.py                    # rebuild every generated index
    python index_builder.py --type tool-registry
    python index_builder.py --force            # overwrite hand-curated indexes too
    python index_builder.py --dry-run          # show what would change
"""

import argparse
import datetime as dt
import json
import re
import sys
from pathlib import Path

MARKER = "<!-- generated by index_builder.py -->"
WIKI = Path(__file__).resolve().parent.parent.parent / "knowledge_base" / "wiki"
TODAY = dt.date.today().isoformat()

try:
    import yaml
    HAS_YAML = True
except ImportError:
    HAS_YAML = False


def parse_article(path: Path) -> dict | None:
    try:
        text = path.read_text(encoding="utf-8", errors="ignore")
    except Exception:
        return None
    if not text.startswith("---"):
        return {"file": path, "fm": {}, "generated": MARKER in text}
    parts = text.split("---", 2)
    if len(parts) < 3:
        return {"file": path, "fm": {}, "generated": MARKER in text}
    fm = {}
    if HAS_YAML:
        try:
            fm = yaml.safe_load(parts[1]) or {}
        except Exception:
            fm = {}
    if not fm:
        for line in parts[1].splitlines():
            if ":" in line:
                k, v = line.split(":", 1)
                fm[k.strip()] = v.strip().strip('"').strip("'")
    return {"file": path, "fm": fm, "generated": MARKER in text}


ID_KEYS = {
    "tool-registry": "tool_id",
    "packer": "packer_id",
    "technique": "technique_id",
    "experiment": "experiment_id",
    "success-trace": "success_trace_id",
    "pattern": "pattern_id",
    "apk-analysis": "analysis_id",
    "knowledge-diff": "diff_id",
}


def rows(md: dict) -> dict:
    fm = md["fm"]
    id_key = ID_KEYS.get(fm.get("type", ""))
    art_id = fm.get(id_key) if id_key else None
    if not art_id:
        for k in ("tool_id", "environment_id", "technique_id", "experiment_id",
                  "success_trace_id", "pattern_id", "analysis_id", "diff_id"):
            if fm.get(k):
                art_id = fm[k]
                break
    out = {
        "id": art_id or md["file"].stem,
        "name": fm.get("name") or md["file"].stem,
        "type": fm.get("type", "?"),
        "topic": fm.get("topic", ""),
        "summary": str(fm.get("llm_summary", ""))[:140],
        "completeness": fm.get("completeness", "?"),
        "verified": fm.get("last_verified", "?"),
        "fm": fm,
    }
    return out


def fmt_list(v) -> str:
    if isinstance(v, list):
        return "[" + ", ".join(str(x) for x in v) + "]"
    return str(v or "—")


def tool_row(r: dict) -> str:
    fm = r["fm"]
    caps = fm.get("capabilities", [])
    cap = ", ".join(caps[:3]) if isinstance(caps, list) else str(caps)[:80]
    return (f"| {r['id']} | {r['name']} | {fm.get('version') or '—'} | {fm.get('category', '—')} "
            f"| {fm.get('host_device', '—')} | {fm.get('availability', '—')} | {cap} |")


def packer_row(r: dict) -> str:
    fm = r["fm"]
    inds = fm.get("indicators", [])
    ind = str(inds[0])[:60] if isinstance(inds, list) and inds else "—"
    return (f"| {r['id']} | {r['name']} | {fm.get('unpacking_status', '—')} "
            f"| {fm.get('confidence', '—')} | {ind} "
            f"| {fmt_list(fm.get('technique_ids', []))} |")


def analysis_row(r: dict) -> str:
    fm = r["fm"]
    sha = str(fm.get("apk_sha256") or "—")
    return (f"| {r['id']} | {fm.get('package_name', '—')} | {sha[:16]}… "
            f"| {fmt_list(fm.get('protection_detected', []))} | {fm.get('status', '—')} "
            f"| {fm.get('bypass_status', '—')} |")


def experiment_row(r: dict) -> str:
    fm = r["fm"]
    return (f"| {r['id']} | {fm.get('analysis_id', '—')} | {fm.get('technique_id', '—')} "
            f"| {fm.get('result', '—')} | {fm.get('verification_status', '—')} "
            f"| {str(fm.get('key_learning', '—'))[:90]} |")


def success_row(r: dict) -> str:
    fm = r["fm"]
    goal = str(fm.get("goal") or r["summary"] or "—")[:70]
    return (f"| {r['id']} | {fm.get('analysis_id', '—')} | {goal} "
            f"| {fm.get('confidence', '—')} | {fmt_list(fm.get('techniques_used', []))} |")


def pattern_row(r: dict) -> str:
    fm = r["fm"]
    return (f"| {r['id']} | {r['name']} | {fm.get('category', '—')} | {fm.get('protection_type', '—')} "
            f"| {fm.get('confidence', '—')} | {fmt_list(fm.get('technique_ids', []))} |")


def diff_row(r: dict) -> str:
    fm = r["fm"]
    return (f"| {r['id']} | {fm.get('analysis_id', '—')} | {fm.get('timestamp', r['verified'])} "
            f"| {fmt_list(fm.get('new_techniques', []))} | {fmt_list(fm.get('updated_techniques', []))} "
            f"| {fmt_list(fm.get('confidence_changes', []))} |")


# type -> (cross index file, header, row fn, columns)
CROSS = {
    "tool-registry": ("_tool-registry-index.md",
                      "| Tool ID | Name | Version | Category | Host/Device | Availability | Key Capabilities |",
                      tool_row),
    "packer": ("_packer-index.md",
               "| Packer ID | Name | Unpacking Status | Confidence | First Indicator | Techniques |",
               packer_row),
    "apk-analysis": ("_apk-index.md",
                     "| Analysis ID | Package | SHA256 | Protections | Status | Verdict |",
                     analysis_row),
    "experiment": ("_experiment-index.md",
                   "| Experiment ID | Analysis | Technique | Result | Verification | Key Learning |",
                   experiment_row),
    "success-trace": ("_success-trace-index.md",
                       "| Trace ID | Analysis | Goal | Confidence | Techniques Used |",
                       success_row),
    "pattern": ("_pattern-index.md",
                "| Pattern ID | Name | Category | Protection Type | Confidence | Techniques |",
                pattern_row),
    "knowledge-diff": ("_knowledge-diff-index.md",
                       "| Diff ID | Analysis | Timestamp | New Techniques | Updated Techniques | Confidence Changes |",
                       diff_row),
}

# topic dir -> label
TOPICS = {
    "tool-registry": "Tool Registry",
    "packers": "Packers",
    "techniques": "Techniques",
    "apks": "APK Analysis",
    "experiments": "Experiments",
    "success-traces": "Success Traces",
    "patterns": "Patterns",
    "knowledge-diffs": "Knowledge Diffs",
}


def build_topic_index(topic: str, articles: list[dict]) -> str:
    lines = [MARKER, f"# {TOPICS.get(topic, topic.title())} — Index", "",
             "## Quick Navigation", f"Looking for... -> browse `{topic}/` articles below.", "",
             "## Articles",
             "| Article | Covers (Summary) | Type | Completeness | Last updated |",
             "|---|---|---|---|---|"]
    for a in sorted(articles, key=lambda x: x["id"]):
        rel = a["file"].relative_to(WIKI).with_suffix("").as_posix()
        lines.append(f"| [[wiki/{rel}]] | {a['summary'] or '—'} | {a['type']} "
                     f"| {a['completeness']} | {a['verified']} |")
    lines += ["", f"**Articles:** {len(articles)} | **Last reindexed:** {TODAY}"]
    return "\n".join(lines) + "\n"


def build_cross(articles: list[dict], header: str, rowfn) -> str:
    lines = [MARKER, f"# Cross-Topic Index — {TODAY}", "", header, "|---|---|---|---|---|---|---|"
             if header.count("|") == 8 else header + "|---|---|---|---|---|---|"]
    # normalize separator to header column count
    ncols = header.count("|") - 1
    lines[3] = header
    lines[4] = "|" + "---|" * ncols
    for a in sorted(articles, key=lambda x: x["id"]):
        lines.append(rowfn(a))
    lines += ["", f"**Entries:** {len(articles)} | **Last reindexed:** {TODAY}"]
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--type", help="only this article type (e.g. tool-registry)")
    ap.add_argument("--force", action="store_true", help="overwrite hand-curated files")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    all_articles = []
    for topic_dir in sorted(p for p in WIKI.iterdir() if p.is_dir()):
        for md in sorted(topic_dir.glob("*.md")):
            if md.name.startswith("_"):
                continue
            a = parse_article(md)
            if a and a["fm"]:
                a["topic_dir"] = topic_dir.name
                all_articles.append(rows(a) | {"topic_dir": topic_dir.name,
                                               "generated": a["generated"], "file": md})

    written, skipped = [], []

    # topic indexes
    for topic, label in TOPICS.items():
        arts = [a for a in all_articles if a["topic_dir"] == topic]
        if not arts:
            continue
        path = WIKI / topic / "_index.md"
        content = build_topic_index(topic, arts)
        if path.exists():
            existing = path.read_text(encoding="utf-8", errors="ignore")
            if MARKER not in existing and not args.force:
                skipped.append(f"{topic}/_index.md (hand-curated)")
                continue
        if not args.dry_run:
            path.write_text(content, encoding="utf-8")
        written.append(f"{topic}/_index.md ({len(arts)})")

    # cross-topic indexes
    for atype, (fname, header, rowfn) in CROSS.items():
        if args.type and args.type != atype:
            continue
        arts = [a for a in all_articles if a["type"] == atype]
        if not arts:
            continue
        path = WIKI / fname
        content = build_cross(arts, header, rowfn)
        if path.exists():
            existing = path.read_text(encoding="utf-8", errors="ignore")
            if MARKER not in existing and not args.force:
                skipped.append(f"{fname} (hand-curated)")
                continue
        if not args.dry_run:
            path.write_text(content, encoding="utf-8")
        written.append(f"{fname} ({len(arts)})")

    print(json.dumps({"written": written, "skipped": skipped, "dry_run": args.dry_run}, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
